[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/jaewoenlee/ML/blob/main/supplementary2_pands92-colab_English.ipynb)

This English notebook is saved locally. The button opens Colab; click **Upload notebook** and select `supplementary2_pands92-colab_English.ipynb`. It does not automatically open or upload this local file.

## Special Appendix 2

# pandas for Data Analysis

### pandas: An Essential Library for Data Analysis

pandas is a Python library that provides many tools for data analysis. Because it makes data easy to manipulate and work with, it is an essential companion when studying deep learning and machine learning. We have combined the pandas manual, the cheat sheet on the pandas website, and other resources to collect the most frequently used pandas functions. Explore these 92 practical pandas recipes that you can use right away.

## A. Creating Data

In [ ]:
# 1. Import the pandas library.
import pandas as pd

In [ ]:
# 2. Create a DataFrame.
df = pd.DataFrame(              # Store the DataFrame in a variable named df.
        {"a" : [4 ,5, 6, 7],    # Specify the column names and store the data as Series.
        "b" : [8, 9, 10, 11],
        "c" : [12, 13, 14, 15]},
        index = [1, 2, 3, 4])   # Set the index to 1,2,3.

In [ ]:
# 3. Display a DataFrame.
df

   a   b   c
1  4   8  12
2  5   9  13
3  6  10  14
4  7  11  15

In [ ]:
# 4. Create a DataFrame with explicitly specified column names.
df = pd.DataFrame(
        [[4, 8, 12],
        [5, 9, 13],
        [6, 10, 14],
        [7, 11, 15]],
        index=[1, 2, 3, 4],
        columns=['a', 'b', 'c'])  # You can specify column names separately.
df

   a   b   c
1  4   8  12
2  5   9  13
3  6  10  14
4  7  11  15

In [ ]:
# 5. Create a DataFrame with a two-level index.
df = pd.DataFrame(
    {"a" : [4 ,5, 6, 7], 
     "b" : [8, 9, 10, 11],
     "c" : [12, 13, 14, 15]},
    index = pd.MultiIndex.from_tuples(      # Specify the index using tuples.
        [('d', 1), ('d', 2), ('e', 1), ('e', 2)],     
        names=['n', 'v']))                  # Specify the index names.
df

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

## B. Sorting Data

In [ ]:
# 6. Sort by the values in a specific column.
df.sort_values('a', ascending=False)  # Set ascending=False to sort in descending order.

     a   b   c
n v
e 2  7  11  15
  1  6  10  14
d 2  5   9  13
  1  4   8  12

In [ ]:
# 7. Rename columns.
df.rename(columns = {'c':'d'})  # Rename column c to d.

     a   b   d
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

In [ ]:
# 8. Reset the index.
df.reset_index()

   n  v  a   b   c
0  d  1  4   8  12
1  d  2  5   9  13
2  e  1  6  10  14
3  e  2  7  11  15

In [ ]:
# 9. Sort by index.
df.sort_index()

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

In [ ]:
# 10. Remove specific columns.
df.drop(columns=['a', 'b'])

      c
n v
d 1  12
  2  13
e 1  14
  2  15

## C. Selecting Rows

In [ ]:
# 11. Display the top rows.
df.head(2)  # Display two rows.

     a  b   c
n v
d 1  4  8  12
  2  5  9  13

In [ ]:
# 12. Display the bottom rows.
df.tail(2)  # Display two rows.

     a   b   c
n v
e 1  6  10  14
  2  7  11  15

In [ ]:
# 13. Select rows using values in a specific column.
df[df["a"] > 4]          # Select rows where column a is greater than 4.

     a   b   c
n v
d 2  5   9  13
e 1  6  10  14
  2  7  11  15

In [ ]:
# 14. Select rows containing a specific value in a given column.
df[df["a"] == 6]       # Select rows where column a contains 6.

     a   b   c
n v
e 1  6  10  14

In [ ]:
# 15. Select rows without a specific value in a given column.
df[df["a"] != 5]        # Select rows where column a does not contain 5.

     a   b   c
n v
d 1  4   8  12
e 1  6  10  14
  2  7  11  15

In [ ]:
# 16. Check whether a given column contains specific numbers.
df[df['a'].isin([4])]  # Specify the desired numbers as a list ([int]).

     a  b   c
n v
d 1  4  8  12

In [ ]:
# 17. Sample a specified fraction of the data.
df.sample(frac=0.75)  # Randomly select the specified fraction each time this runs.

     a   b   c
n v
e 1  6  10  14
d 1  4   8  12
e 2  7  11  15

In [ ]:
# 18. Sample a specified number of records.
df.sample(n=3)  # Randomly select the number specified by n each time this runs.

     a   b   c
n v
d 2  5   9  13
  1  4   8  12
e 2  7  11  15

In [ ]:
# 19. Retrieve the largest values in a specific column.
df.nlargest(3,'a')   # Retrieve the three largest values in column a.

     a   b   c
n v
e 2  7  11  15
  1  6  10  14
d 2  5   9  13

In [ ]:
# 20. Retrieve the smallest values in a specific column.
df.nsmallest(3,'a')   # Retrieve the three smallest values in column a.

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14

## D. Selecting Columns

In [ ]:
# 21. Select by an index range.

# Counting starts at 0, so the first row has index 0 and the fourth row has index 3.
df.iloc[1:4]    # [a:b] selects from index a through index b-1. # Retrieve the three largest values in column a.

     a   b   c
n v
d 2  5   9  13
e 1  6  10  14
  2  7  11  15

In [ ]:
# 22. Select by specifying the starting index.
df.iloc[2:]    # [a:] selects from index a through the last index.

     a   b   c
n v
e 1  6  10  14
  2  7  11  15

In [ ]:
# 23. Select by specifying the ending index.
df.iloc[:3]    # [:b] selects from the beginning through index b-1.

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14

In [ ]:
# 24. Select all indices.
df.iloc[:]    # [:] selects all indices.

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

In [ ]:
# 25. Select specific columns.
df[['a', 'b']]   # Select columns a and b.

     a   b
n v
d 1  4   8
  2  5   9
e 1  6  10
  2  7  11

In [ ]:
# 26. Select columns that satisfy a condition.
df.filter(regex='c')    # Display columns whose names contain the character c.

      c
n v
d 1  12
  2  13
e 1  14
  2  15

In [ ]:
# 27. Select columns that do not contain a specific character.
df.filter(regex='^(?!c$).*')    # Display columns whose names do not contain the character c.

     a   b
n v
d 1  4   8
  2  5   9
e 1  6  10
  2  7  11

## E. Selecting Rows and Columns

In [ ]:
# 28. Select specific rows and columns.
# Use the form df.loc[rows to select,columns to select].
df.loc[:, 'a':'c']     # Select all indices and columns a through c.

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

In [ ]:
# 29. Select specific rows and columns by index.
df.iloc[0:3, [0, 2]]   # Select indices 0 through 2 and columns 0 and 2. (The first column is column 0.)

     a   c
n v
d 1  4  12
  2  5  13
e 1  6  14

In [ ]:
# 30. Select rows and columns that meet a condition in a specific column.
df.loc[df['a'] > 5, ['a', 'c']]  # Display columns a and c for rows where a is greater than 5.

     a   c
n v
e 1  6  14
  2  7  15

In [ ]:
# 31. Retrieve values meeting specific conditions using indices.
df.iat[1, 2]    # Retrieve the value at row index 1, column 2.

13

## F. Handling Duplicate Data

In [ ]:
# Create a DataFrame with duplicate values for this exercise.
df = pd.DataFrame(
    {"a" : [4 ,5, 6, 7, 7], 
     "b" : [8, 9, 10, 11, 11],
     "c" : [12, 13, 14, 15, 15]},
    index = pd.MultiIndex.from_tuples(     
        [('d', 1), ('d', 2), ('e', 1), ('e', 2), ('e',3)],     
        names=['n', 'v']))                 
df

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15
  3  7  11  15

In [ ]:
# 32. Count occurrences of each value in a specific column.
df['a'].value_counts()

7    2
4    1
5    1
6    1
Name: a, dtype: int64

In [ ]:
# 33. Count the rows in a DataFrame.
len(df)

5

In [ ]:
# 34. Count the rows and columns in a DataFrame.
df.shape

(5, 3)

In [ ]:
# 35. Count unique values in a specific column.
df['a'].nunique()

4

In [ ]:
# 36. View the shape of a DataFrame at a glance.
df.describe()

             a         b         c
count  5.00000   5.00000   5.00000
mean   5.80000   9.80000  13.80000
std    1.30384   1.30384   1.30384
min    4.00000   8.00000  12.00000
25%    5.00000   9.00000  13.00000
50%    6.00000  10.00000  14.00000
75%    7.00000  11.00000  15.00000
max    7.00000  11.00000  15.00000

In [ ]:
# 37. Remove duplicate values.
df = df.drop_duplicates()
df

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

## G. Understanding the Data

In [ ]:
# 38. View the sum of each column.
df.sum()

a    22
b    38
c    54
dtype: int64

In [ ]:
# 39. Count the values in each column.
df.count()

a    4
b    4
c    4
dtype: int64

In [ ]:
# 40. View the median of each column.
df.median()

a     5.5
b     9.5
c    13.5
dtype: float64

In [ ]:
# 41. View the mean of a specific column.
df['b'].mean()

9.5

In [ ]:
# 42. View the 25% and 75% quantiles of each column.
df.quantile([0.25,0.75])

         a      b      c
0.25  4.75   8.75  12.75
0.75  6.25  10.25  14.25

In [ ]:
# 43. View the minimum of each column.
df.min()

a     4
b     8
c    12
dtype: int64

In [ ]:
# 44. View the maximum of each column.
df.max()

a     7
b    11
c    15
dtype: int64

In [ ]:
# 45. View the standard deviation of each column.
df.std()

a    1.290994
b    1.290994
c    1.290994
dtype: float64

In [ ]:
# 46. Apply a function to every value in a DataFrame.
import numpy as np
df.apply(np.sqrt)  # Calculate square roots.

            a         b         c
n v
d 1  2.000000  2.828427  3.464102
  2  2.236068  3.000000  3.605551
e 1  2.449490  3.162278  3.741657
  2  2.645751  3.316625  3.872983

## H. Handling Missing Values

In [ ]:
# Use NumPy to create a DataFrame containing null values.

df = pd.DataFrame( 
    {"a" : [4 ,5, 6, np.nan], 
     "b" : [7, 8, np.nan, 9], 
     "c" : [10, np.nan, 11, 12]},    
    index = pd.MultiIndex.from_tuples(
        [('d', 1), ('d', 2), ('e', 1), ('e', 2)],     
        names=['n', 'v']))
df

       a    b     c
n v
d 1  4.0  7.0  10.0
  2  5.0  8.0   NaN
e 1  6.0  NaN  11.0
  2  NaN  9.0  12.0

In [ ]:
# 47. Check for null values.
pd.isnull(df)

         a      b      c
n v
d 1  False  False  False
  2  False  False   True
e 1  False   True  False
  2   True  False  False

In [ ]:
# 48. Check for non-null values.
pd.notnull(df)

         a      b      c
n v
d 1   True   True   True
  2   True   True  False
e 1   True  False   True
  2  False   True   True

In [ ]:
# 49. Delete rows containing null values.
df_notnull = df.dropna()
df_notnull

       a    b     c
n v
d 1  4.0  7.0  10.0

In [ ]:
# 50. Replace null values with a specific value.
df_fillna = df.fillna(13)
df_fillna

        a     b     c
n v
d 1   4.0   7.0  10.0
  2   5.0   8.0  13.0
e 1   6.0  13.0  11.0
  2  13.0   9.0  12.0

In [ ]:
# 51. Replace null values with a calculated result.
df_fillna_mean = df.fillna(df['a'].mean())   # Replace with the mean of column a.
df_fillna_mean

       a    b     c
n v
d 1  4.0  7.0  10.0
  2  5.0  8.0   5.0
e 1  6.0  5.0  11.0
  2  5.0  9.0  12.0

In [ ]:
# Create a DataFrame for the exercise on adding columns.
df = pd.DataFrame(
    {"a" : [4 ,5, 6, 7], 
     "b" : [8, 9, 10, 11],
     "c" : [12, 13, 14, 15]},
    index = pd.MultiIndex.from_tuples(      # Specify the index using tuples.
        [('d', 1), ('d', 2), ('e', 1), ('e', 2)],     
        names=['n', 'v']))                  # Specify the index names.
df

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

## I. Creating New Columns

In [ ]:
# 52. Create a new column based on a condition.
df['sum'] = df['a']+df['b']+df['c']
df

     a   b   c  sum
n v
d 1  4   8  12   24
  2  5   9  13   27
e 1  6  10  14   30
  2  7  11  15   33

In [ ]:
# 53. Use assign() to create a new column based on a condition.
df = df.assign(multiply=lambda df: df['a']*df['b']*df['c'])    # Add the values in columns a,b,c to create column d.
df

     a   b   c  sum  multiply
n v
d 1  4   8  12   24       384
  2  5   9  13   27       585
e 1  6  10  14   30       840
  2  7  11  15   33      1155

In [ ]:
# 54. Divide numerical data into bins.
df['qcut'] = pd.qcut(df['a'], 2, labels=["600이하","600이상"])  # Divide column a into two bins and create a new label for each.
df

     a   b   c  sum  multiply   qcut
n v
d 1  4   8  12   24       384  600이하
  2  5   9  13   27       585  600이하
e 1  6  10  14   30       840  600이상
  2  7  11  15   33      1155  600이상

In [ ]:
# 55. Clip values to specified lower and upper limits.
df['clip'] = df['a'].clip(lower=5,upper=6)  # In column a, change all values of 5 or less to 5 and all values of 6 or more to 6.
df

     a   b   c  sum  multiply   qcut  clip
n v
d 1  4   8  12   24       384  600이하     5
  2  5   9  13   27       585  600이하     5
e 1  6  10  14   30       840  600이상     6
  2  7  11  15   33      1155  600이상     6

In [ ]:
# 56. Retrieve maximum values.
df.max(axis=0)   # axis=0 compares rows; axis=1 compares columns.

a               7
b              11
c              15
sum            33
multiply     1155
qcut        600이상
clip            6
dtype: object

In [ ]:
# 57. Retrieve minimum values.
df.min(axis=0)

a               4
b               8
c              12
sum            24
multiply      384
qcut        600이하
clip            5
dtype: object

## J. Reshaping Rows and Columns

In [ ]:
# Convert columns to rows and rows to columns.

# Create new data for this exercise.
df = pd.DataFrame({'A': {0: 'a', 1: 'b', 2: 'c'},
                   'B': {0: 1, 1: 3, 2: 5},
                   'C': {0: 2, 1: 4, 2: 6}})
df

   A  B  C
0  a  1  2
1  b  3  4
2  c  5  6

In [ ]:
# 58. Convert all columns to rows.
pd.melt(df)

  variable value
0        A     a
1        A     b
2        A     c
3        B     1
4        B     3
5        B     5
6        C     2
7        C     4
8        C     6

In [ ]:
# 59. Move just one column into rows.
pd.melt(df, id_vars=['A'], value_vars=['B'])    # Keep column A as it is and move column B into rows.

   A variable  value
0  a        B      1
1  b        B      3
2  c        B      5

In [ ]:
# 60. Move multiple columns into rows.
df_melt = pd.melt(df, id_vars=['A'], value_vars=['B','C'])    # Keep column A as it is and move columns B and C into rows.
df_melt

   A variable  value
0  a        B      1
1  b        B      3
2  c        B      5
3  a        C      2
4  b        C      4
5  c        C      6

In [ ]:
# 61. Create new columns based on values in a specific column.
df_pivot = df_melt.pivot(index='A', columns='variable', values='value')  # Make column A the new index and arrange columns B and C accordingly.
df_pivot

variable  B  C
A
a         1  2
b         3  4
c         5  6

In [ ]:
# 62. Restore the original data layout.
df_origin = df_pivot.reset_index()  # Reset the index.
df_origin.columns.name = None       # Reset the index column's name.
df_origin

   A  B  C
0  a  1  2
1  b  3  4
2  c  5  6

## K. Concatenating Series

In [ ]:
# Create a Series.
s1 = pd.Series(['a', 'b'])
s1

0    a
1    b
dtype: object

In [ ]:
# Series 2
s2 = pd.Series(['c', 'd'])
s2

0    c
1    d
dtype: object

In [ ]:
# 63. Concatenate Series.
pd.concat([s1, s2])

0    a
1    b
0    c
1    d
dtype: object

In [ ]:
# 64. Create a new index when combining data.
pd.concat([s1, s2], ignore_index=True)

0    a
1    b
2    c
3    d
dtype: object

In [ ]:
# 65. Add a hierarchical index and specify column names.
pd.concat([s1, s2], 
          keys=['s1', 's2'], 
          names=['Series name', 'Row ID'])

Series name  Row ID
s1           0         a
             1         b
s2           0         c
             1         d
dtype: object

## L. Concatenating DataFrames

In [ ]:
# Concatenate DataFrames.

# DataFrame 1
df1 = pd.DataFrame([['a', 1], 
                    ['b', 2]],
                       columns=['letter', 'number'])
df1

  letter  number
0      a       1
1      b       2

In [ ]:
# DataFrame 2
df2 = pd.DataFrame([['c', 3], 
                    ['d', 4]],
                   columns=['letter', 'number'])
df2

  letter  number
0      c       3
1      d       4

In [ ]:
# DataFrame 3
df3 = pd.DataFrame([['c', 3, 'cat'], 
                    ['d', 4, 'dog']],
                       columns=['letter', 'number', 'animal'])
df3

  letter  number animal
0      c       3    cat
1      d       4    dog

In [ ]:
# DataFrame 4
df4 = pd.DataFrame([['bird', 'polly'], 
                    ['monkey', 'george']],
                   columns=['animal', 'name'])
df4

   animal    name
0    bird   polly
1  monkey  george

In [ ]:
# 66. Concatenate DataFrames.
pd.concat([df1, df2])

  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

In [ ]:
# 67. Concatenate two DataFrames with different numbers of columns.
pd.concat([df1, df3])

  letter  number animal
0      a       1    NaN
1      b       2    NaN
0      c       3    cat
1      d       4    dog

In [ ]:
# 68. Combine only the columns shared by both.
pd.concat([df1, df3], join="inner")

  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

In [ ]:
# 69. Combine data with different column names.
pd.concat([df1, df4], axis=1)

  letter  number  animal    name
0      a       1    bird   polly
1      b       2  monkey  george

## M. Merging Data

In [ ]:
# Create DataFrame 1 for this exercise.
adf = pd.DataFrame({"x1" : ["A","B","C"], 
                    "x2": [1,2,3]})
adf

  x1  x2
0  A   1
1  B   2
2  C   3

In [ ]:
# Create DataFrame 2.
bdf = pd.DataFrame({"x1" : ["A","B","D"], 
                    "x3": ["T","F","T"]})
bdf

  x1 x3
0  A  T
1  B  F
2  D  T

In [ ]:
# Create DataFrame 3.
cdf = pd.DataFrame({"x1" : ["B","C","D"], 
                    "x2": [2,3,4]})
cdf

  x1  x2
0  B   2
1  C   3
2  D   4

In [ ]:
# 70. Merge using the left-hand columns as the reference.
pd.merge(adf, bdf, how='left', on='x1')   
# Merge on x1, using the left DataFrame (adf) as the reference.
# Since the left DataFrame adf has no D, the corresponding values become NaN.

  x1  x2   x3
0  A   1    T
1  B   2    F
2  C   3  NaN

In [ ]:
# 71. Merge using the right-hand columns as the reference.
pd.merge(adf, bdf, how='right', on='x1')   
# Merge on x1, using the right DataFrame (bdf) as the reference.
# Since the right DataFrame bdf has no C, the corresponding values become NaN.

  x1   x2 x3
0  A  1.0  T
1  B  2.0  F
2  D  NaN  T

In [ ]:
# 72. Merge only shared values.
pd.merge(adf, bdf, how='inner', on='x1')

  x1  x2 x3
0  A   1  T
1  B   2  F

In [ ]:
# 73. Merge all values.
pd.merge(adf, bdf, how='outer', on='x1')

  x1   x2   x3
0  A  1.0    T
1  B  2.0    F
2  C  3.0  NaN
3  D  NaN    T

In [ ]:
# 74. Compare specific columns and retrieve only records with shared values.
adf[adf.x1.isin(bdf.x1)]  
# Compare specific columns in adf and bdf, retrieving only records with shared values.
# adf.x1 and bdf.x1 share A,B. Display only the corresponding records from adf.

  x1  x2
0  A   1
1  B   2

In [ ]:
# 75. Exclude records with shared values when merging.
adf[~adf.x1.isin(bdf.x1)]  # Display everything except those records.

  x1  x2
2  C   3

In [ ]:
# 76. Merge only records with shared values.
pd.merge(adf, cdf)

  x1  x2
0  B   2
1  C   3

In [ ]:
# 77. Merge everything.
pd.merge(adf, cdf, how='outer')

  x1  x2
0  A   1
1  B   2
2  C   3
3  D   4

In [ ]:
# 78. Indicate where each merged record came from.
pd.merge(adf, cdf, how='outer', indicator=True)

  x1  x2      _merge
0  A   1   left_only
1  B   2        both
2  C   3        both
3  D   4  right_only

In [ ]:
# 79. Keep only the desired merge results.
pd.merge(adf, cdf, how='outer', indicator=True).query('_merge == "left_only"')

  x1  x2     _merge
0  A   1  left_only

In [ ]:
# 80. Remove the merge column.
pd.merge(adf, cdf, how='outer', indicator=True).query('_merge == "left_only"').drop(columns=['_merge'])

  x1  x2
0  A   1

## N. Processing Data

In [ ]:
# Create a DataFrame for this exercise.
df = pd.DataFrame(
        {"a" : [4 ,5, 6, 7],   # Specify the column names and store the data as Series.
        "b" : [8, 9, 10, 11],
        "c" : [12, 13, 14, 15]},
        index = [1, 2, 3, 4])  # Set the index to 1,2,3.
df

   a   b   c
1  4   8  12
2  5   9  13
3  6  10  14
4  7  11  15

In [ ]:
# 81. Shift all rows down by one position.
df.shift(1)

     a     b     c
1  NaN   NaN   NaN
2  4.0   8.0  12.0
3  5.0   9.0  13.0
4  6.0  10.0  14.0

In [ ]:
# 82. Shift all rows up by one position.
df.shift(-1)

     a     b     c
1  5.0   9.0  13.0
2  6.0  10.0  14.0
3  7.0  11.0  15.0
4  NaN   NaN   NaN

In [ ]:
# 83. Calculate cumulative sums from the top row.
df.cumsum()

    a   b   c
1   4   8  12
2   9  17  25
3  15  27  39
4  22  38  54

In [ ]:
# 84. Display cumulative maxima as each row is compared with previous rows.
df.cummax()

   a   b   c
1  4   8  12
2  5   9  13
3  6  10  14
4  7  11  15

In [ ]:
# 85. Display cumulative minima as each row is compared with previous rows.
df.cummin()

   a  b   c
1  4  8  12
2  4  8  12
3  4  8  12
4  4  8  12

In [ ]:
# 85. Calculate cumulative products from the top row.
df.cumprod()

     a     b      c
1    4     8     12
2   20    72    156
3  120   720   2184
4  840  7920  32760

### O. Aggregating by Group

In [ ]:
# Load the data for this exercise.
!git clone https://github.com/taehojo/data.git 

# Load the house price prediction data from Chapter 15 of Deep Learning for Everyone.
df = pd.read_csv("./data/house_train.csv")
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [ ]:
# 87. Define groups and display the record count for each.
df.groupby(by="YrSold").size()   # Group by the year sold, then display the number of records in each group.

YrSold
2006    314
2007    329
2008    304
2009    338
2010    175
dtype: int64

In [ ]:
# 88. Display selected columns after grouping.
df.groupby(by="YrSold")['LotArea'].mean()   # Group by the year sold, then display the garage area for each group.

YrSold
2006    10489.458599
2007    10863.686930
2008    10587.687500
2009    10294.248521
2010    10220.645714
Name: LotArea, dtype: float64

In [ ]:
# 89. Assign ranks using the dense method.
df['SalePrice'].rank(method='dense')   # What is each house price's rank using dense ranking?

0       413.0
1       340.0
2       443.0
3       195.0
4       495.0
        ...
1455    315.0
1456    416.0
1457    528.0
1458    200.0
1459    222.0
Name: SalePrice, Length: 1460, dtype: float64

In [ ]:
# 90. Assign ranks using the minimum method.
df['SalePrice'].rank(method='min')    # What is each house price's rank using minimum ranking?

0       1072.0
1        909.0
2       1135.0
3        490.0
4       1236.0
         ...
1455     828.0
1456    1076.0
1457    1285.0
1458     524.0
1459     591.0
Name: SalePrice, Length: 1460, dtype: float64

In [ ]:
# 91. Express ranks as percentages.
df['SalePrice'].rank(pct=True)    # Express house price ranks as percentages (0=least expensive house, 1=most expensive house).

0       0.734247
1       0.622603
2       0.777740
3       0.342123
4       0.848973
          ...
1455    0.569863
1456    0.738356
1457    0.880137
1458    0.358904
1459    0.404795
Name: SalePrice, Length: 1460, dtype: float64

In [ ]:
# 92. Specify how to handle tied ranks.
df['SalePrice'].rank(method='first')   # When ranks are tied, give the earlier entry the higher rank.

0       1072.0
1        909.0
2       1135.0
3        490.0
4       1236.0
         ...
1455     836.0
1456    1080.0
1457    1285.0
1458     524.0
1459     591.0
Name: SalePrice, Length: 1460, dtype: float64